### ISSUE TITLE
Focus Point for Large Landscape Images

### ISSUE THREAD

**Issue by ccordina** [jonom/silverstripe-focuspoint#15]
I am trying to debug and find a solution for this issue. Currently i have a 2880x1800 image with a focus point ( values Focus X = 0.8333333333333333, Focus Y = -0.6000000000000001) for some reason it is not generating an image cropped around the focus point. In reality it is resizing the image and setting the cropped image to the following, Top, Left, Width, Height (20-0-320-180) values.

Have you ever met this issue?

**Comment by jonom** [comment]
Hi @ccordina, it's hard for me to visualise this - can you post some screen shots of the original image and the focus point, and the resulting output? Keep in mind that FocusPoint doesn't try to zoom in or centre the focus point in the output - all it does is makes sure that the image cropping is biased towards retaining the focus point area of the image, rather than just cropping from the centre.

**Comment by ccordina** [comment]
Hi @jonom  thanks for your quick reply. So i have an image container of 320 x180 and if you see the image below i am testing it on a banner which is quite long... focus point is X = -0.94, Y=-0.22222222222222232, but im getting the resultant cropped image which is not equal to what it should appear.

For portrait images its working fine.. don't know why landscape or longer images in width doesnt work properly or maybe im doing something wrong

![5 5hx46 25wposter](https://cloud.githubusercontent.com/assets/13001145/8286022/7284c6a4-1907-11e5-90bd-b0d2c7b98599.jpg)
![focusimage](https://cloud.githubusercontent.com/assets/13001145/8286031/8819d84c-1907-11e5-8ca9-6991502daf80.png)

**Comment by jonom** [comment]
That looks like a straight up plain old CroppedImage (cropped from the centre) :) did you update your templates to use $CroppedFocusedImage? What is the filename of the output image? It should start with 'CroppedFocusedImage'.
