### ISSUE TITLE
Silvestripe 3.2

### ISSUE THREAD

**Issue by guyvanbael** [jonom/silverstripe-focuspoint#17]
Any plans for a version for Silverstripe 3.2?
CroppedImage has been replaced by Fill....

**Comment by jonom** [comment]
Hi Guy, you should be able to use the current release with 3.2 - are you having trouble? The old Image methods won't be removed until 4.0 so there shouldn't be a compatibility problem. I will update the module at some point but maybe not right away if it's not necessary.

**Comment by guyvanbael** [comment]
Hi, thanks for your reply.
It's not really the old image methods that are causing the problem. The focuswindow isn't showing up when editing the image (screenshot attached).
![schermafbeelding 2015-11-05 om 14 46 44](https://cloud.githubusercontent.com/assets/3098809/10970097/a3e6b4ac-83cc-11e5-88e5-87a07a41e5e3.png)

**Comment by jonom** [comment]
Ah yes, that's caused by a `DataList::byID()` bug in SS 3.2.0. It will be [fixed](https://github.com/silverstripe/silverstripe-framework/pull/4725) in 3.2.1.

If you want to fix this in the mean time you just need to trigger a call to `write()` one time on all your image records like this:

```php
$images = Image::get();
foreach ($images as $i) {
	$i->write();
}
```

This causes the Image table to be populated with any missing records.
