### ISSUE TITLE
Extend GDBackend to overwrite croppedImage

### ISSUE THREAD

**Issue by wernerkrauss** [jonom/silverstripe-focuspoint#6]
How about extending GDBackend class and overwrite croppedresize there to automatically add the great functionality?

**Comment by Martimiz** [comment]
How about creating a class like FocusPointImage extends Image to overwrite CroppedImage(), then use the injector to load the new class instead of the old. Would that work?

**Comment by jonom** [comment]
It might work but I'm reluctant to subclass image as I think this could lead to incompatibility with other modules and custom code. If I force the framework to use a different class instead of Image does that mean other extensions applied to Image would be ignored? Maybe not, but if another module subclassed Image too I think you couldn't use it alongside FocusPoint?

I might be overthinking this or misunderstand how the injector works - please correct me if so :)

**Comment by Martimiz** [comment]
I think any module that wants to change or enhance a core class behaviour runs the risk of conflicting with other modules, no way to totally avoid that I suppose. Thinking things through is always a good thing, I personally wouldn't call that overthinking :)

If someone were to subclass Image and use that subclass in their code, it wouldn't be using your functionality. If someone uses Image, it would. I think :) Extensions to Image would still be extensions to Image, but your  subclass should have access to its functionality....

But hey, it's just one more suggestion to check out, if you really want to override CroppedImage(). I'm quite happy with the way it is now actually :)

Thanks for a really nice pair of modules!

Martine

**Comment by jonom** [comment]
Thanks Martine, I'll try out your suggestion. I'm thinking it should be easy to make this optional actually - I could offer a 'no-conflict' setting that leaves things how they are and requires $CroppedFocusedImage to be used in templates, but by default I could use the injector so that $CroppedImage can be replaced. I'll let you know how it goes!

**Comment by jonom** [comment]
Okay guys this should work on the latest release - requires 3.3. and opt-in with some yml config. See ReadMe for details.

**Comment by jonom** [comment]
In 3.4 this might even let you get focused thumbnails in the CMS. Wouldn't that be a treat? https://github.com/silverstripe/silverstripe-framework/pull/5043
