### ISSUE TITLE
Unnecessary filesystem reads for images

### ISSUE THREAD

**Issue by kinglozzer** [jonom/silverstripe-focuspoint#64]
https://github.com/jonom/silverstripe-focuspoint/blob/09ae334655b0156c91aab0ceb2f2de13a7063d4f/src/FieldType/DBFocusPoint.php#L197-L222

Putting all of this _outside_ of the `$image->manipulateImage(function() { ...` closure means that even if the resampled copy exists already, focuspoint will still check the dimensions of the image. The `getWidth()`/`getHeight()` calls can result in expensive operations - intervention loads the entire image into memory to check the dimensions.

The saving grace here is that the dimensions are cached by SilverStripe once they’ve first been discovered, but if that cache is lost (e.g. after a `dev/build` or a deploy) then focuspoint will trigger re-loading the image into memory to check dimensions even when the resampled copy already exists. Even when the cached dimensions do exist, this adds unnecessary cache reads to each page load.

I had a quick look at refactoring this to move the `getWidth()`/`getHeight()` calls _inside_ the `manipulateImage()` closure. However the width/height are passed to `calculateCrop()`, and the resulting crop data is then used in the variant name. The only way I can spot to fix this would be to adjust the variant name to not use crop data - I _think_ using the requested dimensions and focuspoint x/y co-ordinates should be enough to guarantee uniqueness though...

**Comment by jonom** [comment]
Good catch Loz! Looks like this code is still structured like an SS3 Image method, I hadn't noticed the change in SS4 (where it looks like pretty much everything should go in the `manipulateImage` closure) and didn't realise there was a performance penalty.

> I think using the requested dimensions and focuspoint x/y co-ordinates should be enough to guarantee uniqueness though...

Yes that should be fine. If you're up for it please feel free to refactor and open a PR. Feel free to change whatever you need/want to, if it looks backwards compatible we can do a minor release but otherwise I'm happy to do a major version bump.

**Comment by purplespider** [comment]
Ah ha. So this could be why I've been getting 503 errors due to a site hitting it's 1GB LVE memory limit (PHP limit set to 256GB), at seemingly random times or always on a `flush=1`, which don't occur if I disable focus point.

Any temporary workaround?

**Comment by jonom** [comment]
Reopening because I need to revert the original fix as it broke a test 😢

**Comment by kinglozzer** [comment]
@jonom Sorry I never got round to looking at this! The issue was that the crop data (which changed and broke the tests) is fetched by `calculateCrop()`, which needs the original image dimensions to work. The original image dimensions are cached, but if that cache is cleared (on deploy or flush) it means re-opening the image to fetch them again.

 I can’t spot any nice way around this. I wonder if we might be better to instead propose a change to `silverstripe-assets` to use `getimagesize()` instead of loading a full image resource just to fetch dimensions... either way I think reverting is probably the right move

**Comment by jonom** [comment]
> I wonder if we might be better to instead propose a change to silverstripe-assets to use getimagesize() instead of loading a full image resource just to fetch dimensions

@kinglozzer Yeah if that's possible that would be great. I'm also wondering what the impact of this issue is... are you getting 503 errors like @purplespider ? I'm keen to understand why so much memory is getting used... I would have expected that after one image was processed, the memory was released before going on the next one. If that's not happening I guess you could call that a memory leak and I wonder if it's a fault of this module or if the same thing would happen on any request where lots of images are being resampled (a Silverstripe or Intervention limitation)

**Comment by kinglozzer** [comment]
I’m not sure, my issue wasn’t memory limits (but then we use Imagick instead of GD so wouldn’t expect to hit memory limits) but timeouts if a page had a large number of images.

**Comment by purplespider** [comment]
@kinglozzer I reckon if you checked memory usage just before it timed out, it would be using excessive memory above any specified PHP limits.

In many scenarios, the memory spike may go unnoticed, as it will just use as much memory as it needs, possibly going into swap, so no error occurs unless it hits the max execution time before it finishes. But on hosting such as CloudLinux where there is a hard maximum memory limit per hosting account, it will just hit this limit and then 503, this occurred even when using Imagick.

To confirm, @kinglozzer's fix #73 resolved this issue for me.

**Comment by jonom** [comment]
Sort of related, I'm currently implementing a background-resampling strategy for images on a project. The idea is that you can ask for a resampled image, but you'll only get it if it's already been generated. If not, it doesn't get generated on-the-fly, instead it is queued to be generated later.

The use case would be a page (or a JSON feed) where you have hundreds of resampled images and would rather show a missing or placeholder image than risk a long response time or causing a timeout. Ideally you'd generate images you know you'll need before they are requested, for instance in a related `onAfterWrite()` method.

Wondering if this is something you guys would use - is it worth publishing a module?

**Comment by purplespider** [comment]
> Wondering if this is something you guys would use - is it worth publishing a module?

Certainly sounds an interesting project. Personally, I wouldn't have a need for this, as displaying a placeholder image would be undesirable in my projects, if anything I'd probably prefer to just display the original, non-resampled, image rather than a placeholder.


> Ideally you'd generate images you know you'll need before they are requested, for instance in a related `onAfterWrite()` method.

While I understand the technical reasons for it, it has always struck me as suboptimal that images are resampled on the next page load with Silverstripe, resulting in slow load times the first time a gallery page is accessed for example. So generating them beforehand does appeal. Presumably, `onAfterWrite()` could pass over the page URL to a cronjob to render the page in the background or similar.

**Comment by jonom** [comment]
> Presumably, onAfterWrite() could pass over the page URL to a cronjob to render the page in the background or similar.

@purplespider yeah that's the approach I'm taking. The `onAfterWrite()` (or other trigger) doesn't actually produce the resampled image, it just adds it to a queue.

**Comment by tractorcow** [comment]
You can assign this back to me, I'm going to look at this issue now. I need it for a project that's crashing due to memory issues.

**Comment by tractorcow** [comment]
I think we'll need to cache width / height, but not in way that is really accessible to core silverstripe (without core changes of course).

DBFile would need to store it on a property, but Image could cache it in the DB.

**Comment by micschk** [comment]
> Sort of related, I'm currently implementing a background-resampling strategy for images on a project. The idea is that you can ask for a resampled image, but you'll only get it if it's already been generated. If not, it doesn't get generated on-the-fly, instead it is queued to be generated later.
> 
> The use case would be a page (or a JSON feed) where you have hundreds of resampled images and would rather show a missing or placeholder image than risk a long response time or causing a timeout. Ideally you'd generate images you know you'll need before they are requested, for instance in a related `onAfterWrite()` method.
> 
> Wondering if this is something you guys would use - is it worth publishing a module?

@jonom one approach I once implemented (on a SS3 project) is for images which are not yet resampled in the desired format, to return a reference to a `/resampled/$ImgID/$Format` URL/controller function instead of resampling it on the fly. 

I placed this URL in the session as well, the resampling method then tests if the user has the requested URL in the session (prevent DOS), resamples, and redirects to the actual resampled image URL. 

This results in faster initial loadtimes but also may prevent any memory issues as each image gets resampled in an individual (browser-queued) request with separate memory limit which gets released afterwards.

Did you ever publish your queued resampling code?
