### ISSUE TITLE
V2 to V3 migrations script fails during first dev/build after SS4 upgrade (adding versioned to files)

### ISSUE THREAD

**Issue by michalkleiner** [jonom/silverstripe-focuspoint#89]
Since 3.1.3, if the migration is executed during the same dev/build as when the `Image_Live` and `Image_Versions` tables are created, the migration fails with

```
ERROR [Emergency]: Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:

UPDATE "Image_Live"
 SET "FocusPointX" = "FocusX", "FocusPointY" = "FocusY" * -1

Unknown column 'FocusX' in 'field list'
```

It's possible the migration is triggered before the extra versioning related tables are created.

**Comment by jonom** [comment]
Took me a while to click on what's happening here 😄, but I can see that the [migration scrip](https://github.com/jonom/silverstripe-focuspoint/blob/master/src/Dev/FocusPointMigrationTask.php#L69) is making an assumption that the Live and Versions table would exist, and they would at this point, but it's also assuming that they would have the same fields as the base table, which would not be true in this circumstance, because FocusX and FocusY are not part of the current field spec so wouldn't have been built in to the Live and Versions tables if they didn't exist before this point.

BTW - the only time I could think this would happen is a first time upgrade from SS3 to SS4, where FocusPoint was already installed. Is that the case?

I guess we need to check whether the Live and Versions tables contain the `$from` fields, and omit them from [`$imageTables`](https://github.com/jonom/silverstripe-focuspoint/blob/master/src/Dev/FocusPointMigrationTask.php#L56) if they do not.

Or rather... I wonder if instead of skipping those tables we need to run a different action on them in this scenario. I'm guessing that at this point, the `FocusPointX` and `FocusPointY` fields in the Live and Versions tables will contain the default value for that field (zero I think?), because we haven't yet done the migration to copy the values from the old field names. So if we just skipped this step we might get weird issues with focus points being reset to the centre. So I think we would want to copy the relevant values from the base Image table to each record in the Live and Versions table in that case. Although, I don't know how Silverstripe handles populating records when classes suddenly become Versioned. Possibly it's done in `requireDefaultRecords()` and we'd need to make sure the FocusPoint part happens after this core part. @michalkleiner are you able to confirm any of this? And any interest in opening a PR to fix?

**Comment by michalkleiner** [comment]
Thanks for your reaction, @jonom!

Yes, I can confirm it happened when we ran `dev/build` for the first time after all composer dependencies were upgraded to SS4, including this module. It only became an issue with 3.1.3 which introduced the versioned tables handling, it wasn't a problem with 3.1.2.

As a workaround, we ran two subsequent releases, one with 3.1.2, ran dev/build, then 3.1.3, ran dev/build. It's a one-off thing for us so not a big hassle, though still wanted to flag the issue.

From my perspective, it nearly feels like the migration should either run later or be two-tiered. Checking for the columns on the _Live and _Versions tables would avoid the error, but would likely not copy the values across.

Not sure what the best approach would be here, I tried to look into it within the limited time I had and didn't find any other easy route using `requireDefaultRecords` method for automatic migration.

**Comment by RoyalPulp** [comment]
Hi, 
just got into this issue again !! ...while converting a rather large project from SS3 to SS4 
Any chance, this could be resolved?
Is there any fast workaround?
Thanks, Hendrik

**Comment by RuthAdele** [comment]
Same issue here. Also fixed just by running dev build again.

**Comment by OldStarchy** [comment]
We had some trouble with this trying to deploy to SilverStripe Cloud since a failed dev/build automatically rolls back. Our fix was to replace the migration task (via the injector) with a copy that wraps the content of the `foreach ($imageTables as $imageTable) {` loop with a try/catch.

https://github.com/jonom/silverstripe-focuspoint/blob/c2bd2d9a77435678843be5192014a141404d64f8/src/Dev/FocusPointMigrationTask.php#L68-L77

I guess the initial `isset($fields["{$from}X"]` should be moved to just within this loop and check the relevant table, but I'm not sure it would affect the outcome of the migration too much unless there's some other error that needs proper handling.
